import type { GrantApplication } from "@/lib/types";

export const mockApplications: GrantApplication[] = [
  {
    id: "app-001",
    grantId: "grant-001",
    grantName: "Small Business Innovation Research (SBIR) Phase I",
    agency: "National Science Foundation",
    agencyInitials: "NSF",
    status: "preparing",
    amountRequested: 27_500_000,
    deadline: "2026-06-05",
    submittedDate: null,
    lastUpdated: "2026-03-10",
    notes:
      "Project pitch accepted by NSF under topic IT — invited to submit full proposal. Technical proposal draft 60% complete. Need to finalize budget narrative per NSF guidelines and obtain letter of collaboration from IIT research partner for potential Phase II.",
    documentsUploaded: 3,
    documentsRequired: 5,
    nextStep: "Complete 15-page project description Section 3 — prior research results and preliminary data",
    completionPercentage: 60,
  },
  {
    id: "app-002",
    grantId: "grant-004",
    grantName: "MBDA Capital Readiness Program",
    agency: "Minority Business Development Agency",
    agencyInitials: "MBDA",
    status: "researching",
    amountRequested: 15_000_000,
    deadline: "2026-06-30",
    submittedDate: null,
    lastUpdated: "2026-03-08",
    notes:
      "Contacted Chicago MBDA Business Center (operated by Chicago Urban League) about spring intake cycle. Need to prepare 3-year growth plan and updated financial projections. Waiting for Q1 2026 financials to finalize application package.",
    documentsUploaded: 2,
    documentsRequired: 4,
    nextStep: "Draft 3-year business growth plan with revenue projections and hiring milestones",
    completionPercentage: 25,
  },
  {
    id: "app-003",
    grantId: "grant-003",
    grantName: "SBA 8(a) Business Development Program",
    agency: "U.S. Small Business Administration",
    agencyInitials: "SBA",
    status: "submitted",
    amountRequested: 0,
    deadline: "2026-12-31",
    submittedDate: "2026-02-28",
    lastUpdated: "2026-03-05",
    notes:
      "8(a) certification application submitted via certify.sba.gov on Feb 28. SBA Form 1010, personal financial statements (Form 413), 3 years of tax returns, and capability statement all uploaded. Received confirmation email with tracking number. Processing typically takes 60-90 days. May receive requests for additional documentation during review.",
    documentsUploaded: 5,
    documentsRequired: 5,
    nextStep: "Await SBA review decision — expected by late April. Monitor certify.sba.gov for status updates or document requests.",
    completionPercentage: 100,
  },
];
