import type { DeadlineEvent } from "@/lib/types";

export const mockDeadlines: DeadlineEvent[] = [
  {
    id: "dl-001",
    title: "Cook County Stabilization Grant Deadline",
    date: "2026-03-31",
    type: "grant-deadline",
    relatedId: "grant-016",
    relatedName: "Cook County Small Business Stabilization Grant",
    description: "Final deadline for Cook County stabilization grant applications",
    urgency: "urgent",
  },
  {
    id: "dl-002",
    title: "Chicago SBIF Application Deadline",
    date: "2026-04-15",
    type: "grant-deadline",
    relatedId: "grant-008",
    relatedName: "City of Chicago Small Business Improvement Fund",
    description: "Submit SBIF application with contractor bids",
    urgency: "soon",
  },
  {
    id: "dl-003",
    title: "Q1 Estimated Tax Payment",
    date: "2026-04-15",
    type: "tax-filing",
    relatedId: "",
    relatedName: "IRS Quarterly Estimated Tax",
    description: "Federal and Illinois estimated tax payment due",
    urgency: "soon",
  },
  {
    id: "dl-004",
    title: "DOE Small Business Voucher Deadline",
    date: "2026-04-30",
    type: "grant-deadline",
    relatedId: "grant-004",
    relatedName: "DOE Small Business Voucher Pilot",
    description: "Applications close for DOE voucher program",
    urgency: "soon",
  },
  {
    id: "dl-005",
    title: "Google Black Founders Fund Deadline",
    date: "2026-04-30",
    type: "grant-deadline",
    relatedId: "grant-011",
    relatedName: "Google for Startups Black Founders Fund",
    description: "Entry deadline for Google founders fund",
    urgency: "soon",
  },
  {
    id: "dl-006",
    title: "Chicago NOF Application Due",
    date: "2026-05-01",
    type: "grant-deadline",
    relatedId: "grant-009",
    relatedName: "Chicago Neighborhood Opportunity Fund",
    description: "Submit NOF application with project plan",
    urgency: "upcoming",
  },
  {
    id: "dl-007",
    title: "SBIR Phase I Submission",
    date: "2026-05-15",
    type: "application-due",
    relatedId: "app-001",
    relatedName: "SBIR Phase I Application",
    description: "Complete and submit SBIR Phase I technical proposal",
    urgency: "upcoming",
  },
  {
    id: "dl-008",
    title: "FedEx Grant Contest Entry",
    date: "2026-05-15",
    type: "grant-deadline",
    relatedId: "grant-012",
    relatedName: "FedEx Small Business Grant Contest",
    description: "Submit business story video and application",
    urgency: "upcoming",
  },
  {
    id: "dl-009",
    title: "IL Small Business Dev Grant Due",
    date: "2026-05-31",
    type: "application-due",
    relatedId: "app-002",
    relatedName: "Illinois DCEO Grant Application",
    description: "Submit complete DCEO grant application",
    urgency: "upcoming",
  },
  {
    id: "dl-010",
    title: "Chicago MBE Program Deadline",
    date: "2026-06-01",
    type: "grant-deadline",
    relatedId: "grant-010",
    relatedName: "Chicago MBE/WBE Business Development Program",
    description: "Application deadline for MBE development program",
    urgency: "future",
  },
  {
    id: "dl-011",
    title: "Q2 Estimated Tax Payment",
    date: "2026-06-15",
    type: "tax-filing",
    relatedId: "",
    relatedName: "IRS Quarterly Estimated Tax",
    description: "Federal and Illinois Q2 estimated tax payment due",
    urgency: "future",
  },
  {
    id: "dl-012",
    title: "IL Technology Development Grant Due",
    date: "2026-06-15",
    type: "grant-deadline",
    relatedId: "grant-006",
    relatedName: "Illinois Technology Development Grant",
    description: "ISTC technology grant applications close",
    urgency: "future",
  },
  {
    id: "dl-013",
    title: "MBDA Capital Grant Deadline",
    date: "2026-06-30",
    type: "grant-deadline",
    relatedId: "grant-002",
    relatedName: "MBDA Capital Grant",
    description: "Federal MBDA capital grant applications due",
    urgency: "future",
  },
  {
    id: "dl-014",
    title: "National Urban League Grant Due",
    date: "2026-07-01",
    type: "grant-deadline",
    relatedId: "grant-017",
    relatedName: "National Urban League Entrepreneurship Grant",
    description: "NUL entrepreneurship center grant deadline",
    urgency: "future",
  },
  {
    id: "dl-015",
    title: "MBE Review Committee Decision",
    date: "2026-04-28",
    type: "review-date",
    relatedId: "app-003",
    relatedName: "Chicago MBE/WBE Application Review",
    description: "Expected decision date for MBE application (submitted Feb 28)",
    urgency: "soon",
  },
];
