import type { DeadlineEvent } from "@/lib/types";

export const mockDeadlines: DeadlineEvent[] = [
  // ── March 2026 ──
  {
    id: "dl-001",
    title: "SBA 8(a) Application — Target Submission",
    date: "2026-03-31",
    type: "application-due",
    relatedId: "grant-003",
    relatedName: "SBA 8(a) Business Development Program",
    description: "Target date to submit 8(a) certification application via certify.sba.gov — processing takes 60-90 days",
    urgency: "urgent",
  },

  // ── April 2026 ──
  {
    id: "dl-002",
    title: "Q1 Estimated Tax Payment Due",
    date: "2026-04-15",
    type: "tax-filing",
    relatedId: "",
    relatedName: "IRS Quarterly Estimated Tax",
    description: "Federal (Form 1040-ES) and Illinois estimated tax payment due for Q1 2026",
    urgency: "soon",
  },
  {
    id: "dl-003",
    title: "FedEx Grant Contest — Entries Open",
    date: "2026-04-01",
    type: "grant-deadline",
    relatedId: "grant-016",
    relatedName: "FedEx Small Business Grant Contest",
    description: "Entry period opens — begin preparing business story, photos, and application",
    urgency: "soon",
  },
  {
    id: "dl-004",
    title: "IL DCEO TDA Applications Open",
    date: "2026-04-15",
    type: "grant-deadline",
    relatedId: "grant-009",
    relatedName: "Illinois Technology Development Account (TDA) Program",
    description: "FY2026 TDA application cycle opens at DCEO",
    urgency: "soon",
  },
  {
    id: "dl-005",
    title: "SBIF Application Cycle Deadline",
    date: "2026-04-30",
    type: "grant-deadline",
    relatedId: "grant-011",
    relatedName: "Chicago Small Business Improvement Fund (SBIF)",
    description: "Current SBIF application cycle closes — submit with contractor bids and scope of work",
    urgency: "soon",
  },
  {
    id: "dl-006",
    title: "8(a) Review Decision Expected",
    date: "2026-04-28",
    type: "review-date",
    relatedId: "app-003",
    relatedName: "SBA 8(a) Application Review",
    description: "Expected decision date for 8(a) application if submitted by March 31 (60-day processing)",
    urgency: "soon",
  },

  // ── May 2026 ──
  {
    id: "dl-007",
    title: "Chicago NOF Application Deadline",
    date: "2026-05-15",
    type: "grant-deadline",
    relatedId: "grant-012",
    relatedName: "Chicago Neighborhood Opportunity Fund (NOF)",
    description: "Spring 2026 NOF application cycle closes",
    urgency: "upcoming",
  },
  {
    id: "dl-008",
    title: "FedEx Grant Contest — Entry Deadline",
    date: "2026-05-31",
    type: "grant-deadline",
    relatedId: "grant-016",
    relatedName: "FedEx Small Business Grant Contest",
    description: "Last day to submit entries for the annual FedEx grant contest",
    urgency: "upcoming",
  },

  // ── June 2026 ──
  {
    id: "dl-009",
    title: "NSF SBIR Phase I Full Proposal Due",
    date: "2026-06-05",
    type: "application-due",
    relatedId: "app-001",
    relatedName: "SBIR Phase I Application (NSF)",
    description: "Invited full proposal submission deadline via Research.gov — 5:00 PM local time",
    urgency: "upcoming",
  },
  {
    id: "dl-010",
    title: "Q2 Estimated Tax Payment Due",
    date: "2026-06-15",
    type: "tax-filing",
    relatedId: "",
    relatedName: "IRS Quarterly Estimated Tax",
    description: "Federal and Illinois Q2 estimated tax payment due",
    urgency: "upcoming",
  },
  {
    id: "dl-011",
    title: "Verizon Digital Ready Q2 Grant Window Closes",
    date: "2026-06-30",
    type: "grant-deadline",
    relatedId: "grant-017",
    relatedName: "Verizon Small Business Digital Ready Program",
    description: "Q2 2026 grant application window closes — must complete 2 learning modules first",
    urgency: "future",
  },
  {
    id: "dl-012",
    title: "MBDA Capital Readiness Application Due",
    date: "2026-06-30",
    type: "application-due",
    relatedId: "app-002",
    relatedName: "MBDA Capital Readiness Program",
    description: "Spring cycle application due for Chicago MBDA Business Center services",
    urgency: "future",
  },
  {
    id: "dl-013",
    title: "IL Technology Development Account Deadline",
    date: "2026-06-30",
    type: "grant-deadline",
    relatedId: "grant-009",
    relatedName: "Illinois Technology Development Account (TDA) Program",
    description: "FY2026 TDA applications due to DCEO",
    urgency: "future",
  },

  // ── July–September 2026 ──
  {
    id: "dl-014",
    title: "DOE SBIR Phase I Deadline",
    date: "2026-07-15",
    type: "grant-deadline",
    relatedId: "grant-006",
    relatedName: "SBIR Phase I — Department of Energy",
    description: "DOE SBIR Release 2 full applications due via PAMS",
    urgency: "future",
  },
  {
    id: "dl-015",
    title: "Visa Everywhere Initiative Deadline",
    date: "2026-07-31",
    type: "grant-deadline",
    relatedId: "grant-018",
    relatedName: "Visa Everywhere Initiative",
    description: "North America regional applications close",
    urgency: "future",
  },
  {
    id: "dl-016",
    title: "IL SBIR/STTR Matching Funds Deadline",
    date: "2026-08-31",
    type: "grant-deadline",
    relatedId: "grant-007",
    relatedName: "Illinois SBIR/STTR Matching Funds Program",
    description: "DCEO matching funds applications due with federal SBIR/STTR award documentation",
    urgency: "future",
  },
  {
    id: "dl-017",
    title: "NIH STTR Phase I Receipt Date",
    date: "2026-09-05",
    type: "grant-deadline",
    relatedId: "grant-002",
    relatedName: "Small Business Technology Transfer (STTR) Phase I",
    description: "Standard receipt date for NIH STTR Phase I applications",
    urgency: "future",
  },
  {
    id: "dl-018",
    title: "Q3 Estimated Tax Payment Due",
    date: "2026-09-15",
    type: "tax-filing",
    relatedId: "",
    relatedName: "IRS Quarterly Estimated Tax",
    description: "Federal and Illinois Q3 estimated tax payment due",
    urgency: "future",
  },
];
