import type { GrantMatch } from "@/lib/types";

export const mockGrants: GrantMatch[] = [
  {
    id: "grant-001",
    name: "Small Business Innovation Research (SBIR) Phase I",
    agency: "National Science Foundation",
    agencyInitials: "NSF",
    type: "federal",
    category: "grant",
    status: "open",
    amountMin: 25_000_000,
    amountMax: 27_500_000,
    averageAward: 26_000_000,
    deadline: "2026-05-15",
    matchScore: 92,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Small business (< 500 employees)", met: true, explanation: "12 employees — well under threshold" },
      { criterion: "US-based company", met: true, explanation: "Chicago, IL" },
      { criterion: "Technology/R&D focus", met: true, explanation: "NAICS 541512 — Computer Systems Design" },
      { criterion: "Principal investigator employed", met: true, explanation: "Owner can serve as PI" },
    ],
    shortDescription: "Federal funding for early-stage R&D in science and technology with commercial potential.",
    fullDescription: "The SBIR Phase I program provides funding to small businesses to conduct research and development on innovative technologies. Phase I awards support feasibility studies and proof-of-concept development. Successful Phase I awardees may apply for Phase II funding up to $1M.",
    requirements: ["Business plan", "Technical proposal", "Budget justification", "Prior research summary"],
    documentsRequired: [
      { name: "SAM.gov Registration", status: "have", description: "Active registration in System for Award Management" },
      { name: "Technical Proposal", status: "need", description: "Detailed R&D plan (max 15 pages)" },
      { name: "Budget Narrative", status: "need", description: "Itemized budget with justifications" },
      { name: "Company Financials", status: "have", description: "Last 2 years of financial statements" },
    ],
    applicationUrl: "https://www.sbir.gov/apply",
    tags: ["R&D", "technology", "innovation", "federal"],
    isFavorited: true,
    pastAwardees: 2400,
    contactEmail: "sbir@nsf.gov",
    keyDates: [
      { label: "Application Opens", date: "2026-03-01", description: "Portal opens for submissions" },
      { label: "Deadline", date: "2026-05-15", description: "Final submission deadline 5:00 PM ET" },
      { label: "Awards Announced", date: "2026-08-15", description: "Notification of selected awardees" },
    ],
    similarProgramIds: ["grant-002", "grant-003"],
  },
  {
    id: "grant-002",
    name: "Minority Business Development Agency Capital Grant",
    agency: "Minority Business Development Agency",
    agencyInitials: "MBDA",
    type: "federal",
    category: "grant",
    status: "open",
    amountMin: 5_000_000,
    amountMax: 25_000_000,
    averageAward: 15_000_000,
    deadline: "2026-06-30",
    matchScore: 97,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Minority-owned business", met: true, explanation: "Certified minority-owned" },
      { criterion: "Operational for 2+ years", met: true, explanation: "Founded 2022 — 4 years operational" },
      { criterion: "Revenue under $5M", met: true, explanation: "$1.8M annual revenue" },
      { criterion: "Growth-oriented business", met: true, explanation: "Technology sector with expansion plans" },
    ],
    shortDescription: "Capital and technical assistance for minority-owned businesses seeking growth and expansion.",
    fullDescription: "The MBDA Capital Grant program provides financial assistance to minority-owned businesses to support growth, expansion, and job creation. Funds can be used for equipment, hiring, technology upgrades, and market expansion. The program includes mentorship and technical assistance.",
    requirements: ["Minority ownership certification", "Business plan", "Growth projections", "Job creation plan"],
    documentsRequired: [
      { name: "MBE Certification", status: "have", description: "Minority Business Enterprise certification" },
      { name: "Business Plan", status: "need", description: "3-year growth plan with milestones" },
      { name: "Financial Statements", status: "have", description: "Audited financials for last 2 years" },
      { name: "Tax Returns", status: "have", description: "Last 3 years of business tax returns" },
    ],
    applicationUrl: "https://www.mbda.gov/grants",
    tags: ["minority-owned", "capital", "growth", "federal"],
    isFavorited: true,
    pastAwardees: 850,
    contactEmail: "grants@mbda.gov",
    keyDates: [
      { label: "Application Opens", date: "2026-04-01", description: "Submit through Grants.gov" },
      { label: "Deadline", date: "2026-06-30", description: "Applications due by 11:59 PM ET" },
      { label: "Awards Announced", date: "2026-09-15", description: "Grant recipients notified" },
    ],
    similarProgramIds: ["grant-005", "grant-008"],
  },
  {
    id: "grant-003",
    name: "NIST Manufacturing Extension Partnership",
    agency: "National Institute of Standards and Technology",
    agencyInitials: "NIST",
    type: "federal",
    category: "grant",
    status: "open",
    amountMin: 10_000_000,
    amountMax: 50_000_000,
    averageAward: 30_000_000,
    deadline: "2026-07-31",
    matchScore: 78,
    matchStrength: "possible",
    eligibilityReasons: [
      { criterion: "Small/medium manufacturer or tech company", met: true, explanation: "IT services with development capabilities" },
      { criterion: "US-based operations", met: true, explanation: "Chicago, IL" },
      { criterion: "Focus on innovation/productivity", met: true, explanation: "Technology-driven services" },
      { criterion: "Manufacturing component", met: false, explanation: "Primarily services — may need to demonstrate manufacturing aspect" },
    ],
    shortDescription: "Support for small manufacturers and tech companies to innovate and improve competitiveness.",
    fullDescription: "The MEP program helps small and medium-sized manufacturers and technology companies improve their competitiveness through innovation, technology adoption, and workforce development.",
    requirements: ["Innovation plan", "Competitiveness assessment", "Workforce development plan"],
    documentsRequired: [
      { name: "Innovation Proposal", status: "need", description: "Detailed innovation and improvement plan" },
      { name: "Competitiveness Assessment", status: "need", description: "Current state analysis" },
      { name: "Financial Statements", status: "have", description: "Last 2 years" },
    ],
    applicationUrl: "https://www.nist.gov/mep",
    tags: ["innovation", "technology", "manufacturing", "federal"],
    isFavorited: false,
    pastAwardees: 1200,
    contactEmail: "mep@nist.gov",
    keyDates: [
      { label: "Deadline", date: "2026-07-31", description: "Final submission" },
      { label: "Awards Announced", date: "2026-10-01", description: "Award notifications" },
    ],
    similarProgramIds: ["grant-001"],
  },
  {
    id: "grant-004",
    name: "DOE Small Business Voucher Pilot",
    agency: "Department of Energy",
    agencyInitials: "DOE",
    type: "federal",
    category: "grant",
    status: "open",
    amountMin: 5_000_000,
    amountMax: 30_000_000,
    averageAward: 15_000_000,
    deadline: "2026-04-30",
    matchScore: 65,
    matchStrength: "possible",
    eligibilityReasons: [
      { criterion: "Small business (< 500 employees)", met: true, explanation: "12 employees" },
      { criterion: "Technology development", met: true, explanation: "IT services and development" },
      { criterion: "Energy technology focus", met: false, explanation: "Not primarily energy-focused — explore clean tech angle" },
    ],
    shortDescription: "Access to DOE national laboratories for clean energy technology development.",
    fullDescription: "The Small Business Voucher Pilot provides small businesses access to DOE national laboratory expertise and facilities for clean energy technology development and testing.",
    requirements: ["Technology description", "Lab partnership proposal", "Commercial plan"],
    documentsRequired: [
      { name: "Technology Brief", status: "need", description: "Description of clean energy technology" },
      { name: "Lab Partnership Plan", status: "need", description: "Proposed collaboration with DOE lab" },
    ],
    applicationUrl: "https://www.energy.gov/sbv",
    tags: ["energy", "clean-tech", "R&D", "federal"],
    isFavorited: false,
    pastAwardees: 400,
    contactEmail: "sbv@energy.gov",
    keyDates: [
      { label: "Deadline", date: "2026-04-30", description: "Applications close" },
    ],
    similarProgramIds: ["grant-001"],
  },
  {
    id: "grant-005",
    name: "Illinois Small Business Development Grant",
    agency: "Illinois Department of Commerce & Economic Opportunity",
    agencyInitials: "DCEO",
    type: "state",
    category: "grant",
    status: "open",
    amountMin: 1_000_000,
    amountMax: 15_000_000,
    averageAward: 7_500_000,
    deadline: "2026-05-31",
    matchScore: 95,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Illinois-based business", met: true, explanation: "Located in Chicago, IL" },
      { criterion: "Under 50 employees", met: true, explanation: "12 employees" },
      { criterion: "Revenue under $3M", met: true, explanation: "$1.8M annual revenue" },
      { criterion: "Operational for 1+ years", met: true, explanation: "4 years in operation" },
    ],
    shortDescription: "State funding for Illinois small businesses focused on growth, hiring, and economic development.",
    fullDescription: "The DCEO Small Business Development Grant supports Illinois small businesses with funding for growth initiatives including hiring, equipment, technology adoption, and market expansion. Priority given to businesses in underserved communities.",
    requirements: ["Illinois business registration", "Growth plan", "Job creation commitment"],
    documentsRequired: [
      { name: "IL Business Registration", status: "have", description: "Active registration with IL Secretary of State" },
      { name: "Growth Plan", status: "need", description: "12-month growth plan with metrics" },
      { name: "Tax Returns", status: "have", description: "Last 2 years Illinois tax returns" },
      { name: "Job Creation Plan", status: "need", description: "Planned new hires and positions" },
    ],
    applicationUrl: "https://www.illinois.gov/dceo/grants",
    tags: ["Illinois", "growth", "hiring", "state"],
    isFavorited: true,
    pastAwardees: 350,
    contactEmail: "grants@illinois.gov",
    keyDates: [
      { label: "Application Opens", date: "2026-03-15", description: "Online portal opens" },
      { label: "Deadline", date: "2026-05-31", description: "Applications due" },
      { label: "Awards", date: "2026-07-31", description: "Award notifications" },
    ],
    similarProgramIds: ["grant-002", "grant-006"],
  },
  {
    id: "grant-006",
    name: "Illinois Technology Development Grant",
    agency: "Illinois Science & Technology Coalition",
    agencyInitials: "ISTC",
    type: "state",
    category: "grant",
    status: "open",
    amountMin: 5_000_000,
    amountMax: 20_000_000,
    averageAward: 12_000_000,
    deadline: "2026-06-15",
    matchScore: 88,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Illinois technology company", met: true, explanation: "IT services in Chicago" },
      { criterion: "Active R&D program", met: true, explanation: "$220K annual R&D spend" },
      { criterion: "Under 100 employees", met: true, explanation: "12 employees" },
    ],
    shortDescription: "Funding for Illinois tech companies developing innovative products and services.",
    fullDescription: "Supports technology companies in Illinois with R&D funding, commercialization support, and access to university partnerships for innovative product development.",
    requirements: ["R&D documentation", "Product roadmap", "University partnership (optional)"],
    documentsRequired: [
      { name: "R&D Documentation", status: "have", description: "Current R&D activities and spend" },
      { name: "Product Roadmap", status: "need", description: "Technology development timeline" },
      { name: "Patent/IP Documentation", status: "na", description: "Existing patents or applications" },
    ],
    applicationUrl: "https://www.istcoalition.org/grants",
    tags: ["technology", "R&D", "innovation", "Illinois"],
    isFavorited: false,
    pastAwardees: 120,
    contactEmail: "grants@istcoalition.org",
    keyDates: [
      { label: "Deadline", date: "2026-06-15", description: "Applications due" },
    ],
    similarProgramIds: ["grant-001", "grant-005"],
  },
  {
    id: "grant-007",
    name: "Illinois Advantage Workforce Grant",
    agency: "Illinois Department of Commerce & Economic Opportunity",
    agencyInitials: "DCEO",
    type: "state",
    category: "subsidy",
    status: "rolling",
    amountMin: 500_000,
    amountMax: 5_000_000,
    averageAward: 2_500_000,
    deadline: "2026-12-31",
    matchScore: 82,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Illinois employer", met: true, explanation: "Chicago-based" },
      { criterion: "Hiring or training employees", met: true, explanation: "4 new hires last year" },
      { criterion: "Commitment to workforce development", met: true, explanation: "Growing team" },
    ],
    shortDescription: "Reimbursement for employee training and workforce development costs.",
    fullDescription: "Provides reimbursement grants to Illinois employers for costs associated with training new and existing employees. Covers tuition, materials, and trainer costs.",
    requirements: ["Training plan", "Employee roster", "Cost documentation"],
    documentsRequired: [
      { name: "Training Plan", status: "need", description: "Detailed training curriculum" },
      { name: "Employee Roster", status: "have", description: "Current employee list" },
    ],
    applicationUrl: "https://www.illinois.gov/dceo/workforce",
    tags: ["workforce", "training", "Illinois", "subsidy"],
    isFavorited: false,
    pastAwardees: 500,
    contactEmail: "workforce@illinois.gov",
    keyDates: [
      { label: "Rolling", date: "2026-12-31", description: "Applications accepted on rolling basis" },
    ],
    similarProgramIds: ["grant-005"],
  },
  {
    id: "grant-008",
    name: "City of Chicago Small Business Improvement Fund",
    agency: "City of Chicago Department of Business Affairs",
    agencyInitials: "BACP",
    type: "local",
    category: "grant",
    status: "open",
    amountMin: 1_000_000,
    amountMax: 15_000_000,
    averageAward: 8_000_000,
    deadline: "2026-04-15",
    matchScore: 90,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Located in Chicago", met: true, explanation: "Chicago, IL 60607" },
      { criterion: "Small business (< 50 employees)", met: true, explanation: "12 employees" },
      { criterion: "In eligible TIF district", met: true, explanation: "West Loop TIF district eligible" },
    ],
    shortDescription: "Grants for permanent building improvements in TIF-funded areas of Chicago.",
    fullDescription: "The SBIF program provides grants to small businesses and property owners for permanent building improvements. Funded through Tax Increment Financing (TIF), the program covers up to 50% of eligible project costs.",
    requirements: ["Property in TIF district", "Improvement plan", "Contractor bids"],
    documentsRequired: [
      { name: "Lease Agreement", status: "have", description: "Current lease or ownership docs" },
      { name: "Improvement Plan", status: "need", description: "Detailed scope of improvements" },
      { name: "Contractor Bids", status: "need", description: "Minimum 2 competitive bids" },
    ],
    applicationUrl: "https://www.chicago.gov/sbif",
    tags: ["Chicago", "improvement", "TIF", "local"],
    isFavorited: true,
    pastAwardees: 200,
    contactEmail: "sbif@cityofchicago.org",
    keyDates: [
      { label: "Deadline", date: "2026-04-15", description: "Next application cycle closes" },
      { label: "Awards", date: "2026-06-01", description: "Approved projects notified" },
    ],
    similarProgramIds: ["grant-009", "grant-010"],
  },
  {
    id: "grant-009",
    name: "Chicago Neighborhood Opportunity Fund",
    agency: "City of Chicago",
    agencyInitials: "NOF",
    type: "local",
    category: "grant",
    status: "open",
    amountMin: 2_500_000,
    amountMax: 25_000_000,
    averageAward: 12_500_000,
    deadline: "2026-05-01",
    matchScore: 75,
    matchStrength: "possible",
    eligibilityReasons: [
      { criterion: "Chicago-based business", met: true, explanation: "Located in Chicago" },
      { criterion: "Located in qualifying neighborhood", met: false, explanation: "West Loop may not qualify — check eligibility map" },
      { criterion: "Revenue under $4M", met: true, explanation: "$1.8M revenue" },
    ],
    shortDescription: "Investment in commercial projects in Chicago's underserved neighborhoods.",
    fullDescription: "The NOF provides grants for commercial development projects in underinvested areas of Chicago. Funds support construction, renovation, and business expansion in qualifying neighborhoods on the South and West sides.",
    requirements: ["Project in qualifying area", "Business plan", "Community impact statement"],
    documentsRequired: [
      { name: "Location Verification", status: "need", description: "Proof of qualifying neighborhood location" },
      { name: "Project Plan", status: "need", description: "Development or expansion plan" },
    ],
    applicationUrl: "https://www.chicago.gov/nof",
    tags: ["Chicago", "neighborhood", "development", "local"],
    isFavorited: false,
    pastAwardees: 150,
    contactEmail: "nof@cityofchicago.org",
    keyDates: [
      { label: "Deadline", date: "2026-05-01", description: "Applications due" },
    ],
    similarProgramIds: ["grant-008"],
  },
  {
    id: "grant-010",
    name: "Chicago MBE/WBE Business Development Program",
    agency: "City of Chicago Office of Diversity",
    agencyInitials: "CDOL",
    type: "local",
    category: "grant",
    status: "open",
    amountMin: 2_000_000,
    amountMax: 10_000_000,
    averageAward: 5_000_000,
    deadline: "2026-06-01",
    matchScore: 93,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Certified MBE/WBE", met: true, explanation: "Minority-owned business" },
      { criterion: "Chicago-based", met: true, explanation: "Chicago, IL" },
      { criterion: "Operational for 1+ years", met: true, explanation: "4 years operational" },
      { criterion: "Under $5M revenue", met: true, explanation: "$1.8M revenue" },
    ],
    shortDescription: "Business development grants and mentorship for certified MBE/WBE firms in Chicago.",
    fullDescription: "Supports certified Minority Business Enterprises and Women Business Enterprises with grants for capacity building, technology, marketing, and business development. Includes access to procurement opportunities and mentorship.",
    requirements: ["MBE/WBE certification", "Development plan", "Capacity assessment"],
    documentsRequired: [
      { name: "MBE Certification", status: "have", description: "City of Chicago MBE certification" },
      { name: "Development Plan", status: "need", description: "Business development roadmap" },
      { name: "Capacity Assessment", status: "need", description: "Current capabilities and gaps" },
    ],
    applicationUrl: "https://www.chicago.gov/diversity/mbe",
    tags: ["MBE", "diversity", "Chicago", "local"],
    isFavorited: false,
    pastAwardees: 100,
    contactEmail: "diversity@cityofchicago.org",
    keyDates: [
      { label: "Deadline", date: "2026-06-01", description: "Applications due" },
    ],
    similarProgramIds: ["grant-002", "grant-008"],
  },
  {
    id: "grant-011",
    name: "Google for Startups Black Founders Fund",
    agency: "Google for Startups",
    agencyInitials: "GFS",
    type: "private",
    category: "grant",
    status: "open",
    amountMin: 5_000_000,
    amountMax: 10_000_000,
    averageAward: 10_000_000,
    deadline: "2026-04-30",
    matchScore: 70,
    matchStrength: "possible",
    eligibilityReasons: [
      { criterion: "Black-founded company", met: false, explanation: "Minority-owned but specific ethnicity requirement — verify eligibility" },
      { criterion: "Technology company", met: true, explanation: "IT services and development" },
      { criterion: "US-based", met: true, explanation: "Chicago, IL" },
    ],
    shortDescription: "Non-dilutive funding for Black-founded startups in the US.",
    fullDescription: "Google for Startups provides cash awards (non-dilutive), Google Cloud credits, and support from Google teams to Black-founded tech startups.",
    requirements: ["Application form", "Pitch deck", "Company metrics"],
    documentsRequired: [
      { name: "Pitch Deck", status: "need", description: "Company overview and traction" },
      { name: "Metrics Summary", status: "need", description: "Revenue, growth, team size" },
    ],
    applicationUrl: "https://startup.google.com/blackfounders",
    tags: ["diversity", "technology", "startup", "private"],
    isFavorited: false,
    pastAwardees: 76,
    contactEmail: "startups@google.com",
    keyDates: [
      { label: "Deadline", date: "2026-04-30", description: "Applications close" },
    ],
    similarProgramIds: ["grant-012"],
  },
  {
    id: "grant-012",
    name: "FedEx Small Business Grant Contest",
    agency: "FedEx",
    agencyInitials: "FEDEX",
    type: "private",
    category: "grant",
    status: "open",
    amountMin: 1_500_000,
    amountMax: 5_000_000,
    averageAward: 2_500_000,
    deadline: "2026-05-15",
    matchScore: 60,
    matchStrength: "worth-exploring",
    eligibilityReasons: [
      { criterion: "US-based small business", met: true, explanation: "Chicago, IL" },
      { criterion: "6+ months in operation", met: true, explanation: "4 years" },
      { criterion: "For-profit entity", met: true, explanation: "LLC" },
    ],
    shortDescription: "Annual grant contest open to all US small businesses with compelling stories.",
    fullDescription: "The FedEx Small Business Grant Contest awards grants annually to small businesses nationwide. Winners are selected based on business innovation, community impact, and growth potential.",
    requirements: ["Online application", "Business story video", "Financial summary"],
    documentsRequired: [
      { name: "Business Video", status: "need", description: "2-minute business story video" },
      { name: "Application Form", status: "need", description: "Online submission form" },
    ],
    applicationUrl: "https://www.fedex.com/en-us/small-business/grant-contest.html",
    tags: ["contest", "small-business", "private"],
    isFavorited: false,
    pastAwardees: 12,
    contactEmail: "grants@fedex.com",
    keyDates: [
      { label: "Deadline", date: "2026-05-15", description: "Entry deadline" },
    ],
    similarProgramIds: ["grant-011"],
  },
  {
    id: "grant-013",
    name: "SBA 7(a) Small Business Loan Program",
    agency: "Small Business Administration",
    agencyInitials: "SBA",
    type: "federal",
    category: "loan",
    status: "rolling",
    amountMin: 25_000_000,
    amountMax: 500_000_000,
    averageAward: 100_000_000,
    deadline: "2026-12-31",
    matchScore: 85,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Small business by SBA standards", met: true, explanation: "Under $7.5M revenue threshold for NAICS 541512" },
      { criterion: "For-profit US business", met: true, explanation: "LLC in Chicago" },
      { criterion: "Demonstrated ability to repay", met: true, explanation: "$1.8M revenue supports loan repayment" },
    ],
    shortDescription: "SBA-guaranteed loans for working capital, equipment, and business expansion.",
    fullDescription: "The 7(a) loan program is the SBA's primary program for providing financial assistance to small businesses. Loans can be used for working capital, equipment, real estate, and business expansion.",
    requirements: ["Business plan", "Financial statements", "Personal financial statement", "Collateral description"],
    documentsRequired: [
      { name: "Business Plan", status: "need", description: "Comprehensive plan with projections" },
      { name: "Financial Statements", status: "have", description: "Last 3 years" },
      { name: "Personal Financial Statement", status: "need", description: "SBA Form 413" },
    ],
    applicationUrl: "https://www.sba.gov/7a",
    tags: ["loan", "SBA", "capital", "federal"],
    isFavorited: false,
    pastAwardees: 50000,
    contactEmail: "7aloan@sba.gov",
    keyDates: [
      { label: "Rolling", date: "2026-12-31", description: "Applications accepted year-round" },
    ],
    similarProgramIds: [],
  },
  {
    id: "grant-014",
    name: "Illinois Broadband Infrastructure Grant",
    agency: "Illinois Office of Broadband",
    agencyInitials: "IOB",
    type: "state",
    category: "grant",
    status: "open",
    amountMin: 10_000_000,
    amountMax: 50_000_000,
    averageAward: 25_000_000,
    deadline: "2026-08-15",
    matchScore: 55,
    matchStrength: "worth-exploring",
    eligibilityReasons: [
      { criterion: "Illinois technology company", met: true, explanation: "Chicago-based IT services" },
      { criterion: "Broadband/connectivity focus", met: false, explanation: "Not primary focus — explore digital infrastructure angle" },
    ],
    shortDescription: "Funding for broadband infrastructure deployment and digital connectivity solutions.",
    fullDescription: "Supports companies deploying broadband infrastructure and providing digital connectivity solutions across Illinois, with focus on underserved areas.",
    requirements: ["Infrastructure plan", "Coverage map", "Community partnership letters"],
    documentsRequired: [
      { name: "Infrastructure Plan", status: "need", description: "Deployment strategy" },
      { name: "Coverage Map", status: "need", description: "Proposed coverage area" },
    ],
    applicationUrl: "https://www.illinois.gov/broadband",
    tags: ["broadband", "infrastructure", "Illinois", "technology"],
    isFavorited: false,
    pastAwardees: 45,
    contactEmail: "broadband@illinois.gov",
    keyDates: [
      { label: "Deadline", date: "2026-08-15", description: "Applications close" },
    ],
    similarProgramIds: ["grant-006"],
  },
  {
    id: "grant-015",
    name: "Comcast RISE Investment Fund",
    agency: "Comcast",
    agencyInitials: "RISE",
    type: "private",
    category: "grant",
    status: "rolling",
    amountMin: 500_000,
    amountMax: 1_000_000,
    averageAward: 1_000_000,
    deadline: "2026-12-31",
    matchScore: 80,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Small business owned by person of color", met: true, explanation: "Minority-owned business" },
      { criterion: "US-based", met: true, explanation: "Chicago, IL" },
      { criterion: "Operational for 1+ years", met: true, explanation: "4 years" },
    ],
    shortDescription: "Grants, marketing support, and technology upgrades for businesses owned by people of color.",
    fullDescription: "Comcast RISE provides grants along with marketing, technology, and media support for small businesses owned by people of color. Selected recipients receive a combination of financial grants and in-kind services.",
    requirements: ["Online application", "Business description", "Impact statement"],
    documentsRequired: [
      { name: "Application Form", status: "need", description: "Online submission" },
      { name: "Business Description", status: "need", description: "Overview of business and goals" },
    ],
    applicationUrl: "https://www.comcastrise.com",
    tags: ["diversity", "technology", "marketing", "private"],
    isFavorited: false,
    pastAwardees: 13000,
    contactEmail: "rise@comcast.com",
    keyDates: [
      { label: "Rolling", date: "2026-12-31", description: "Applications accepted monthly" },
    ],
    similarProgramIds: ["grant-011"],
  },
  {
    id: "grant-016",
    name: "Cook County Small Business Stabilization Grant",
    agency: "Cook County Bureau of Economic Development",
    agencyInitials: "CBED",
    type: "local",
    category: "grant",
    status: "closing-soon",
    amountMin: 500_000,
    amountMax: 5_000_000,
    averageAward: 2_000_000,
    deadline: "2026-03-31",
    matchScore: 87,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Cook County business", met: true, explanation: "Chicago is in Cook County" },
      { criterion: "Under 50 employees", met: true, explanation: "12 employees" },
      { criterion: "Revenue under $3M", met: true, explanation: "$1.8M revenue" },
    ],
    shortDescription: "Emergency grants for Cook County small businesses for operational stability and growth.",
    fullDescription: "Provides stabilization grants to small businesses in Cook County for operational expenses, technology upgrades, and business continuity planning.",
    requirements: ["Cook County business license", "Revenue documentation", "Use of funds plan"],
    documentsRequired: [
      { name: "Business License", status: "have", description: "Active Cook County license" },
      { name: "Revenue Documentation", status: "have", description: "Bank statements or tax returns" },
      { name: "Use of Funds Plan", status: "need", description: "How grant funds will be used" },
    ],
    applicationUrl: "https://www.cookcountyil.gov/grants",
    tags: ["Cook County", "stabilization", "local"],
    isFavorited: false,
    pastAwardees: 250,
    contactEmail: "grants@cookcountyil.gov",
    keyDates: [
      { label: "Deadline", date: "2026-03-31", description: "CLOSING SOON — applications due" },
    ],
    similarProgramIds: ["grant-008"],
  },
  {
    id: "grant-017",
    name: "National Urban League Entrepreneurship Center Grant",
    agency: "National Urban League",
    agencyInitials: "NUL",
    type: "private",
    category: "grant",
    status: "open",
    amountMin: 2_500_000,
    amountMax: 7_500_000,
    averageAward: 5_000_000,
    deadline: "2026-07-01",
    matchScore: 72,
    matchStrength: "possible",
    eligibilityReasons: [
      { criterion: "Minority-owned business", met: true, explanation: "Minority-owned" },
      { criterion: "Technology or professional services", met: true, explanation: "IT services" },
      { criterion: "Revenue under $5M", met: true, explanation: "$1.8M" },
    ],
    shortDescription: "Business development grants and mentorship through the Urban League network.",
    fullDescription: "The National Urban League provides grants and mentorship to minority-owned businesses through its Entrepreneurship Center network. Includes access to capital, technical assistance, and business education.",
    requirements: ["Application form", "Business plan", "Mentorship commitment"],
    documentsRequired: [
      { name: "Application", status: "need", description: "Online application form" },
      { name: "Business Plan", status: "need", description: "Current business plan" },
    ],
    applicationUrl: "https://nul.org/entrepreneurship",
    tags: ["minority", "mentorship", "development", "private"],
    isFavorited: false,
    pastAwardees: 200,
    contactEmail: "entrepreneurship@nul.org",
    keyDates: [
      { label: "Deadline", date: "2026-07-01", description: "Applications due" },
    ],
    similarProgramIds: ["grant-002", "grant-011"],
  },
  {
    id: "grant-018",
    name: "Illinois Export Development Grant",
    agency: "Illinois DCEO Trade Office",
    agencyInitials: "DCEO",
    type: "state",
    category: "grant",
    status: "open",
    amountMin: 500_000,
    amountMax: 5_000_000,
    averageAward: 2_000_000,
    deadline: "2026-09-30",
    matchScore: 45,
    matchStrength: "worth-exploring",
    eligibilityReasons: [
      { criterion: "Illinois-based company", met: true, explanation: "Chicago, IL" },
      { criterion: "Product or service exportable", met: true, explanation: "IT services could be delivered internationally" },
      { criterion: "Current export activity", met: false, explanation: "No current export activity reported" },
    ],
    shortDescription: "Funding for Illinois businesses to develop international trade and export capabilities.",
    fullDescription: "Supports Illinois businesses in developing international markets through trade show attendance, market research, export compliance training, and international marketing.",
    requirements: ["Export plan", "Market analysis", "Trade show registration (if applicable)"],
    documentsRequired: [
      { name: "Export Plan", status: "need", description: "International market development strategy" },
      { name: "Market Analysis", status: "need", description: "Target market research" },
    ],
    applicationUrl: "https://www.illinois.gov/dceo/trade",
    tags: ["export", "international", "trade", "Illinois"],
    isFavorited: false,
    pastAwardees: 80,
    contactEmail: "trade@illinois.gov",
    keyDates: [
      { label: "Deadline", date: "2026-09-30", description: "Applications due" },
    ],
    similarProgramIds: [],
  },
];
