import type { GrantMatch } from "@/lib/types";

export const mockGrants: GrantMatch[] = [
  // ──────────────────────────────────────────────
  //  FEDERAL PROGRAMS (6)
  // ──────────────────────────────────────────────
  {
    id: "grant-001",
    name: "Small Business Innovation Research (SBIR) Phase I",
    agency: "National Science Foundation",
    agencyInitials: "NSF",
    type: "federal",
    category: "grant",
    status: "open",
    amountMin: 25_000_000,
    amountMax: 27_500_000,
    averageAward: 27_500_000,
    deadline: "2026-06-05",
    matchScore: 92,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Small business (< 500 employees)", met: true, explanation: "12 employees — well under the 500-employee SBA threshold" },
      { criterion: "Organized as for-profit US company", met: true, explanation: "LLC registered in Illinois" },
      { criterion: "Principal investigator primarily employed by firm", met: true, explanation: "Owner/CTO can serve as PI with >51% employment" },
      { criterion: "R&D work performed in the US", met: true, explanation: "All operations in Chicago, IL" },
    ],
    shortDescription: "Up to $275K for Phase I feasibility research in science and engineering with commercial potential.",
    fullDescription: "The NSF SBIR Phase I program funds small businesses to perform feasibility-stage R&D on innovative technologies aligned with NSF's mission areas, including Information Technology (topic area IT). Phase I awards are fixed-amount grants of up to $275,000 for 6-12 months. Successful Phase I awardees may apply for Phase II awards up to $1,000,000. NSF SBIR does not require a university partner, unlike STTR.",
    requirements: ["Project pitch (required before full proposal)", "Full proposal via Research.gov", "Budget justification", "Biographical sketches", "Current and pending support forms"],
    documentsRequired: [
      { name: "SAM.gov Registration", status: "have", description: "Active System for Award Management registration with valid UEI" },
      { name: "Project Pitch", status: "have", description: "3-page pitch submitted via Research.gov for topic suitability" },
      { name: "Full Technical Proposal", status: "need", description: "15-page project description including objectives, R&D plan, and commercialization strategy" },
      { name: "Budget Justification", status: "need", description: "Detailed budget with line-item justifications per NSF guidelines" },
      { name: "Company Financials", status: "have", description: "Last 2 years of audited financial statements" },
    ],
    applicationUrl: "https://www.research.gov/proposalprep/#/landing",
    tags: ["R&D", "technology", "innovation", "federal", "SBIR"],
    isFavorited: true,
    pastAwardees: 2400,
    contactEmail: "sbir@nsf.gov",
    keyDates: [
      { label: "Project Pitch Window", date: "2026-03-01", description: "Submit project pitch via Research.gov for invitation to submit full proposal" },
      { label: "Full Proposal Deadline", date: "2026-06-05", description: "Invited full proposals due by 5:00 PM submitter's local time" },
      { label: "Expected Awards", date: "2026-11-01", description: "Award notifications typically 6 months after submission" },
    ],
    similarProgramIds: ["grant-002", "grant-003"],
  },
  {
    id: "grant-002",
    name: "Small Business Technology Transfer (STTR) Phase I",
    agency: "National Institutes of Health",
    agencyInitials: "NIH",
    type: "federal",
    category: "grant",
    status: "open",
    amountMin: 15_000_000,
    amountMax: 27_500_000,
    averageAward: 22_500_000,
    deadline: "2026-09-05",
    matchScore: 79,
    matchStrength: "possible",
    eligibilityReasons: [
      { criterion: "Small business (< 500 employees)", met: true, explanation: "12 employees" },
      { criterion: "US-based for-profit company", met: true, explanation: "Chicago, IL LLC" },
      { criterion: "Partnership with research institution", met: false, explanation: "Would need to establish formal partnership with a university or nonprofit research institution (at least 30% of work)" },
      { criterion: "Research topic alignment", met: true, explanation: "Health IT, cybersecurity for health data, or AI/ML for healthcare are eligible NIH topics" },
    ],
    shortDescription: "Up to $275K for cooperative R&D between small businesses and research institutions.",
    fullDescription: "The NIH STTR Phase I program requires formal collaboration between a small business and a US research institution (university, federal lab, or nonprofit). The research institution must perform at least 30% of the work. STTR is ideal for commercializing university research. NIH topics include health IT, biomedical informatics, cybersecurity, and data analytics for healthcare.",
    requirements: ["Research institution partnership agreement", "PHS 398 application forms", "Specific aims page", "Research strategy", "Budget with subaward to research partner"],
    documentsRequired: [
      { name: "SAM.gov Registration", status: "have", description: "Active SAM registration with UEI" },
      { name: "Research Partnership Agreement", status: "need", description: "Signed IP agreement with research institution partner" },
      { name: "Specific Aims Page", status: "need", description: "1-page summary of research objectives" },
      { name: "Research Strategy", status: "need", description: "6-page research plan per NIH format" },
    ],
    applicationUrl: "https://grants.nih.gov/grants/guide/pa-files/PA-24-247.html",
    tags: ["R&D", "health-IT", "university-partnership", "federal", "STTR"],
    isFavorited: false,
    pastAwardees: 1500,
    contactEmail: "SBIRinquiries@mail.nih.gov",
    keyDates: [
      { label: "Receipt Date", date: "2026-09-05", description: "Standard receipt date for STTR Phase I applications" },
      { label: "Review", date: "2027-01-15", description: "Scientific peer review by NIH study section" },
      { label: "Earliest Start", date: "2027-04-01", description: "Earliest anticipated award date" },
    ],
    similarProgramIds: ["grant-001"],
  },
  {
    id: "grant-003",
    name: "SBA 8(a) Business Development Program",
    agency: "U.S. Small Business Administration",
    agencyInitials: "SBA",
    type: "federal",
    category: "incentive",
    status: "rolling",
    amountMin: 0,
    amountMax: 0,
    averageAward: 0,
    deadline: "2026-12-31",
    matchScore: 95,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Socially disadvantaged individual(s) own 51%+", met: true, explanation: "Minority-owned business qualifies as socially disadvantaged" },
      { criterion: "Economically disadvantaged (personal net worth < $850K)", met: true, explanation: "Owner likely qualifies based on business size/revenue" },
      { criterion: "Small business by SBA size standards", met: true, explanation: "$1.8M revenue — under $34M threshold for NAICS 541512" },
      { criterion: "In business for at least 2 years", met: true, explanation: "Founded 2022 — 4 years operational" },
    ],
    shortDescription: "9-year federal certification program providing sole-source contracts, mentorship, and training for disadvantaged small businesses.",
    fullDescription: "The SBA 8(a) program is a 9-year business development program for small disadvantaged businesses. Participants can receive sole-source federal contracts up to $4.5M (services) without competitive bidding, mentorship from experienced firms, management and technical assistance, and access to surplus government property. This is a certification, not a direct grant — the value comes from access to set-aside federal contracts. IT services firms with 8(a) certification are highly sought for government technology contracts.",
    requirements: ["SBA Form 1010", "Personal financial statements (SBA Form 413)", "Business financial statements", "Tax returns (3 years)", "Resume of disadvantaged owner(s)"],
    documentsRequired: [
      { name: "SBA Form 1010", status: "need", description: "8(a) Business Development application (available on certify.sba.gov)" },
      { name: "Personal Financial Statement", status: "need", description: "SBA Form 413 for each disadvantaged owner" },
      { name: "Business Tax Returns", status: "have", description: "Last 3 years of federal tax returns" },
      { name: "MBE Certification", status: "have", description: "Existing minority business certification supports application" },
      { name: "Capability Statement", status: "need", description: "Company capabilities, past performance, NAICS codes" },
    ],
    applicationUrl: "https://certify.sba.gov/",
    tags: ["certification", "federal-contracts", "disadvantaged", "federal", "8(a)"],
    isFavorited: true,
    pastAwardees: 10000,
    contactEmail: "8aquestions@sba.gov",
    keyDates: [
      { label: "Rolling Enrollment", date: "2026-12-31", description: "Applications accepted year-round via certify.sba.gov" },
      { label: "Processing Time", date: "2026-06-01", description: "Typical processing takes 60-90 days from complete application" },
    ],
    similarProgramIds: ["grant-004"],
  },
  {
    id: "grant-004",
    name: "MBDA Capital Readiness Program",
    agency: "Minority Business Development Agency",
    agencyInitials: "MBDA",
    type: "federal",
    category: "grant",
    status: "open",
    amountMin: 5_000_000,
    amountMax: 25_000_000,
    averageAward: 15_000_000,
    deadline: "2026-06-30",
    matchScore: 93,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Minority-owned business", met: true, explanation: "Certified minority-owned enterprise" },
      { criterion: "Revenue-generating business", met: true, explanation: "$1.8M annual revenue" },
      { criterion: "Growth-oriented with expansion plans", met: true, explanation: "Technology sector with hiring plans" },
      { criterion: "Located near MBDA Business Center", met: true, explanation: "Chicago MBDA Business Center serves the region" },
    ],
    shortDescription: "Capital access and business development assistance for minority-owned firms through MBDA's national network.",
    fullDescription: "The MBDA Capital Readiness Program connects minority business enterprises (MBEs) with capital, contracts, and markets. Through its national network of Business Centers, MBDA provides one-on-one business consulting, access to capital through loan packaging assistance, help with government and private-sector procurement, and strategic growth planning. The Chicago MBDA Business Center (operated by the Chicago Urban League) specifically serves Illinois MBEs with direct consulting and capital readiness workshops.",
    requirements: ["Business registration", "Minority ownership documentation", "Financial statements", "Business plan or growth strategy"],
    documentsRequired: [
      { name: "MBE Certification", status: "have", description: "Minority Business Enterprise certification from any certifying body" },
      { name: "Business Plan", status: "need", description: "Current business plan with 3-year growth projections" },
      { name: "Financial Statements", status: "have", description: "Last 2 years of P&L, balance sheet, and cash flow statements" },
      { name: "Tax Returns", status: "have", description: "Last 3 years of business tax returns" },
    ],
    applicationUrl: "https://www.mbda.gov/mbda-programs/business-centers",
    tags: ["minority-owned", "capital", "consulting", "federal"],
    isFavorited: true,
    pastAwardees: 3500,
    contactEmail: "chicago@mbda.gov",
    keyDates: [
      { label: "Intake Open", date: "2026-04-01", description: "Spring intake cycle opens for new clients at Chicago MBDA Business Center" },
      { label: "Application Due", date: "2026-06-30", description: "Spring cycle applications due" },
      { label: "Services Begin", date: "2026-08-01", description: "Selected businesses begin receiving consulting services" },
    ],
    similarProgramIds: ["grant-003", "grant-010"],
  },
  {
    id: "grant-005",
    name: "SBA Community Advantage Loan Program",
    agency: "U.S. Small Business Administration",
    agencyInitials: "SBA",
    type: "federal",
    category: "loan",
    status: "rolling",
    amountMin: 5_000_000,
    amountMax: 35_000_000,
    averageAward: 15_000_000,
    deadline: "2026-12-31",
    matchScore: 88,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Small business in underserved market", met: true, explanation: "Minority-owned business qualifies as underserved market" },
      { criterion: "Meets SBA size standards", met: true, explanation: "12 employees, $1.8M revenue — well under thresholds" },
      { criterion: "For-profit US business", met: true, explanation: "LLC in Chicago, IL" },
      { criterion: "Demonstrated ability to repay", met: true, explanation: "$1.8M revenue with positive cash flow supports repayment" },
    ],
    shortDescription: "SBA-backed loans up to $350K through mission-focused CDFIs, specifically for businesses in underserved communities.",
    fullDescription: "The SBA Community Advantage loan program provides loans up to $350,000 through Community Development Financial Institutions (CDFIs) and mission-based lenders. Unlike traditional SBA 7(a) loans, Community Advantage loans are specifically designed for small businesses in underserved markets — including minority-owned, women-owned, and veteran-owned businesses. The program features more flexible underwriting, lower fees, and lenders who specialize in working with diverse entrepreneurs. In Chicago, participating lenders include Accion and the Chicago Community Loan Fund.",
    requirements: ["Business plan", "Financial statements", "Personal financial statement (SBA Form 413)", "Tax returns"],
    documentsRequired: [
      { name: "Business Plan", status: "need", description: "Comprehensive plan with revenue projections" },
      { name: "Financial Statements", status: "have", description: "Last 2 years of P&L and balance sheets" },
      { name: "Personal Financial Statement", status: "need", description: "SBA Form 413 for each owner with 20%+ ownership" },
      { name: "Business Tax Returns", status: "have", description: "Last 3 years of federal and state returns" },
    ],
    applicationUrl: "https://www.sba.gov/funding-programs/loans/lender-match",
    tags: ["loan", "SBA", "CDFI", "underserved", "federal"],
    isFavorited: false,
    pastAwardees: 8000,
    contactEmail: "answerdesk@sba.gov",
    keyDates: [
      { label: "Rolling", date: "2026-12-31", description: "Applications accepted year-round through participating CDFI lenders" },
    ],
    similarProgramIds: ["grant-003"],
  },
  {
    id: "grant-006",
    name: "SBIR Phase I — Department of Energy",
    agency: "U.S. Department of Energy",
    agencyInitials: "DOE",
    type: "federal",
    category: "grant",
    status: "open",
    amountMin: 20_000_000,
    amountMax: 25_000_000,
    averageAward: 20_000_000,
    deadline: "2026-07-15",
    matchScore: 62,
    matchStrength: "worth-exploring",
    eligibilityReasons: [
      { criterion: "Small business (< 500 employees)", met: true, explanation: "12 employees" },
      { criterion: "US-based for-profit entity", met: true, explanation: "Chicago, IL LLC" },
      { criterion: "Technology with energy applications", met: false, explanation: "Core business is IT services — would need to frame work around energy-sector cybersecurity, smart grid software, or building energy management" },
      { criterion: "PI primarily employed by firm", met: true, explanation: "Owner/CTO can serve as PI" },
    ],
    shortDescription: "Up to $250K for early-stage R&D in energy technologies including cybersecurity, AI, and advanced computing.",
    fullDescription: "DOE SBIR Phase I awards support feasibility research in energy-related technologies. Relevant topic areas for IT companies include cybersecurity for energy infrastructure, artificial intelligence for grid optimization, advanced computing, and building energy management software. DOE releases specific topics annually and proposals must align with published topics. Phase I awards are up to $250,000 for 6-12 months.",
    requirements: ["DOE SBIR/STTR application via PAMS", "Technical proposal", "Budget justification", "Commercialization plan"],
    documentsRequired: [
      { name: "SAM.gov Registration", status: "have", description: "Active SAM registration required" },
      { name: "Technical Volume", status: "need", description: "25-page max technical proposal per DOE format" },
      { name: "Commercialization Plan", status: "need", description: "Strategy for bringing technology to market" },
    ],
    applicationUrl: "https://science.osti.gov/sbir",
    tags: ["energy", "cybersecurity", "R&D", "federal", "SBIR"],
    isFavorited: false,
    pastAwardees: 800,
    contactEmail: "SBIR-STTR@science.doe.gov",
    keyDates: [
      { label: "Topics Released", date: "2026-04-01", description: "FY2026 Release 2 topics published" },
      { label: "Deadline", date: "2026-07-15", description: "Full applications due via PAMS" },
      { label: "Awards", date: "2026-12-01", description: "Phase I award notifications" },
    ],
    similarProgramIds: ["grant-001"],
  },

  // ──────────────────────────────────────────────
  //  ILLINOIS STATE PROGRAMS (4)
  // ──────────────────────────────────────────────
  {
    id: "grant-007",
    name: "Illinois SBIR/STTR Matching Funds Program",
    agency: "Illinois Department of Commerce & Economic Opportunity",
    agencyInitials: "DCEO",
    type: "state",
    category: "grant",
    status: "open",
    amountMin: 5_000_000,
    amountMax: 10_000_000,
    averageAward: 7_500_000,
    deadline: "2026-08-31",
    matchScore: 90,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Illinois-based small business", met: true, explanation: "Located in Chicago, IL" },
      { criterion: "Received or applying for federal SBIR/STTR Phase I", met: true, explanation: "Currently preparing NSF SBIR Phase I application (grant-001)" },
      { criterion: "Fewer than 500 employees", met: true, explanation: "12 employees" },
    ],
    shortDescription: "Illinois provides up to $100K in matching funds to companies that receive federal SBIR or STTR Phase I awards.",
    fullDescription: "The Illinois DCEO SBIR/STTR Matching Funds Program provides dollar-for-dollar matching grants (up to $100,000) to Illinois small businesses that receive federal SBIR or STTR Phase I awards. This effectively increases total Phase I funding by up to 40%. The program is designed to strengthen Illinois' innovation economy by helping small tech companies bridge the gap between Phase I and Phase II funding. Companies must be headquartered in Illinois and maintain operations in the state.",
    requirements: ["Federal SBIR/STTR Phase I award letter", "Illinois business registration", "Matching funds application through DCEO"],
    documentsRequired: [
      { name: "Federal Award Letter", status: "need", description: "Official Phase I award notice from federal agency" },
      { name: "IL Business Registration", status: "have", description: "Active Illinois Secretary of State registration" },
      { name: "Project Summary", status: "need", description: "1-page summary of funded research project" },
      { name: "Budget for Matching Funds", status: "need", description: "How state matching funds will be used" },
    ],
    applicationUrl: "https://dceo.illinois.gov/sbdc/sbirmatchingfunds.html",
    tags: ["SBIR", "matching-funds", "R&D", "Illinois", "state"],
    isFavorited: true,
    pastAwardees: 200,
    contactEmail: "ceo.sbdcgrants@illinois.gov",
    keyDates: [
      { label: "Application Window", date: "2026-05-01", description: "FY2026 application window opens" },
      { label: "Deadline", date: "2026-08-31", description: "Applications must be received with federal award documentation" },
      { label: "Awards", date: "2026-10-31", description: "Matching fund awards announced" },
    ],
    similarProgramIds: ["grant-001", "grant-002"],
  },
  {
    id: "grant-008",
    name: "Advantage Illinois — Participation Loan Program",
    agency: "Illinois Department of Commerce & Economic Opportunity",
    agencyInitials: "DCEO",
    type: "state",
    category: "loan",
    status: "rolling",
    amountMin: 5_000_000,
    amountMax: 75_000_000,
    averageAward: 20_000_000,
    deadline: "2026-12-31",
    matchScore: 82,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Illinois-based small business", met: true, explanation: "Chicago, IL" },
      { criterion: "For-profit company", met: true, explanation: "LLC" },
      { criterion: "Job creation or retention commitment", met: true, explanation: "Growing team with 4 recent hires" },
      { criterion: "Cannot obtain conventional financing alone", met: true, explanation: "As a small minority-owned firm, may have difficulty accessing traditional bank loans at favorable terms" },
    ],
    shortDescription: "State-backed participation loans up to $750K with reduced interest rates for Illinois small businesses creating jobs.",
    fullDescription: "Advantage Illinois is the state's primary small business lending program. Through the Participation Loan Program, DCEO partners with banks and CDFIs to provide below-market-rate financing. The state contributes a portion of the loan at 0-3% interest, reducing the blended rate for the borrower. Funds can be used for working capital, equipment, technology, and leasehold improvements. Minority-owned and women-owned businesses receive priority consideration.",
    requirements: ["Bank or CDFI partnership", "Business plan", "Job creation plan", "Financial projections"],
    documentsRequired: [
      { name: "Bank Application", status: "need", description: "Application through participating lender (bank or CDFI)" },
      { name: "Business Plan", status: "need", description: "Plan demonstrating use of funds and growth strategy" },
      { name: "Financial Statements", status: "have", description: "Last 2 years of business financials" },
      { name: "Job Creation Commitment", status: "need", description: "Plan showing jobs to be created or retained" },
    ],
    applicationUrl: "https://dceo.illinois.gov/expandrelocate/advantageillinois.html",
    tags: ["loan", "workforce", "Illinois", "state"],
    isFavorited: false,
    pastAwardees: 600,
    contactEmail: "ceo.advantageil@illinois.gov",
    keyDates: [
      { label: "Rolling", date: "2026-12-31", description: "Applications accepted on rolling basis through participating lenders" },
    ],
    similarProgramIds: ["grant-005"],
  },
  {
    id: "grant-009",
    name: "Illinois Technology Development Account (TDA) Program",
    agency: "Illinois Department of Commerce & Economic Opportunity",
    agencyInitials: "DCEO",
    type: "state",
    category: "grant",
    status: "open",
    amountMin: 2_500_000,
    amountMax: 10_000_000,
    averageAward: 5_000_000,
    deadline: "2026-06-30",
    matchScore: 85,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Illinois technology company", met: true, explanation: "IT services company in Chicago" },
      { criterion: "Active R&D or technology development", met: true, explanation: "$220K annual R&D spend on software/systems" },
      { criterion: "Under 100 employees", met: true, explanation: "12 employees" },
      { criterion: "Under $4M revenue", met: true, explanation: "$1.8M revenue" },
    ],
    shortDescription: "Up to $100K for Illinois tech companies to fund R&D, prototype development, and technology commercialization.",
    fullDescription: "The Technology Development Account program supports early-stage and growing Illinois technology companies with grants for research, development, and commercialization activities. Eligible expenses include prototype development, intellectual property protection, market research for tech products, software development, and hiring technical staff. The program is administered through DCEO's Office of Entrepreneurship, Innovation and Technology.",
    requirements: ["Technology development plan", "Budget and timeline", "Illinois business registration", "R&D documentation"],
    documentsRequired: [
      { name: "Technology Development Plan", status: "need", description: "Detailed plan for R&D activities and commercialization path" },
      { name: "R&D Expenditure Documentation", status: "have", description: "Current R&D spending records and activities" },
      { name: "IL Business Registration", status: "have", description: "Active Illinois registration" },
      { name: "Budget and Timeline", status: "need", description: "Itemized budget for proposed technology development" },
    ],
    applicationUrl: "https://dceo.illinois.gov/aboutdceo/grantopportunities.html",
    tags: ["technology", "R&D", "innovation", "Illinois", "state"],
    isFavorited: false,
    pastAwardees: 150,
    contactEmail: "ceo.techdevelopment@illinois.gov",
    keyDates: [
      { label: "Application Opens", date: "2026-04-15", description: "FY2026 application cycle opens" },
      { label: "Deadline", date: "2026-06-30", description: "Applications due" },
      { label: "Awards", date: "2026-09-01", description: "Award notifications sent" },
    ],
    similarProgramIds: ["grant-001", "grant-007"],
  },
  {
    id: "grant-010",
    name: "Economic Development for a Growing Economy (EDGE) Tax Credit",
    agency: "Illinois Department of Commerce & Economic Opportunity",
    agencyInitials: "DCEO",
    type: "state",
    category: "tax-credit",
    status: "rolling",
    amountMin: 0,
    amountMax: 0,
    averageAward: 0,
    deadline: "2026-12-31",
    matchScore: 72,
    matchStrength: "possible",
    eligibilityReasons: [
      { criterion: "Illinois business creating or retaining jobs", met: true, explanation: "Chicago-based with active hiring" },
      { criterion: "Capital investment in Illinois", met: true, explanation: "Ongoing technology and equipment investments" },
      { criterion: "Demonstrable competition from other states", met: false, explanation: "Would need to show that expansion could occur outside Illinois to qualify" },
      { criterion: "Net positive fiscal impact to Illinois", met: true, explanation: "Growing payroll and tax base" },
    ],
    shortDescription: "Illinois income tax credits for businesses making capital investments and creating jobs in the state.",
    fullDescription: "The EDGE Tax Credit program provides Illinois income tax credits to businesses that commit to creating or retaining jobs and making capital investments in Illinois. Credits are calculated as a percentage of the income tax withholdings of new or retained employees. Agreements typically run 5-10 years. Companies must demonstrate that the project would not occur in Illinois without the incentive (competitive consideration). DCEO evaluates each project based on job quality, capital investment, community impact, and the company's financial condition.",
    requirements: ["EDGE application through DCEO", "Job creation/retention plan", "Capital investment plan", "Competitive analysis showing other state options"],
    documentsRequired: [
      { name: "EDGE Application", status: "need", description: "Formal application through DCEO" },
      { name: "Job Creation Plan", status: "need", description: "Detailed plan for new jobs with salary levels" },
      { name: "Capital Investment Plan", status: "need", description: "Planned investments in Illinois operations" },
      { name: "Financial Statements", status: "have", description: "Company financials demonstrating viability" },
    ],
    applicationUrl: "https://dceo.illinois.gov/expandrelocate/edgetaxcredit.html",
    tags: ["tax-credit", "jobs", "investment", "Illinois", "state"],
    isFavorited: false,
    pastAwardees: 400,
    contactEmail: "ceo.edge@illinois.gov",
    keyDates: [
      { label: "Rolling", date: "2026-12-31", description: "Applications reviewed on rolling basis by DCEO" },
    ],
    similarProgramIds: [],
  },

  // ──────────────────────────────────────────────
  //  CHICAGO / COOK COUNTY LOCAL PROGRAMS (4)
  // ──────────────────────────────────────────────
  {
    id: "grant-011",
    name: "Chicago Small Business Improvement Fund (SBIF)",
    agency: "City of Chicago Department of Planning and Development",
    agencyInitials: "DPD",
    type: "local",
    category: "grant",
    status: "open",
    amountMin: 1_000_000,
    amountMax: 15_000_000,
    averageAward: 6_000_000,
    deadline: "2026-04-30",
    matchScore: 88,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Business or property in eligible TIF district", met: true, explanation: "West Loop area includes active TIF districts" },
      { criterion: "Small business tenant or property owner", met: true, explanation: "Nexus Digital Solutions is a tenant in commercial space" },
      { criterion: "Permanent building improvements planned", met: true, explanation: "Could apply for office buildout, HVAC, electrical, ADA improvements" },
    ],
    shortDescription: "Grants covering up to 50% of permanent building improvement costs (max $150K) for businesses in Chicago TIF districts.",
    fullDescription: "The Small Business Improvement Fund (SBIF) is one of Chicago's most popular grant programs. It provides grants to small businesses and property owners in designated Tax Increment Financing (TIF) districts for permanent building improvements. Eligible improvements include HVAC, plumbing, electrical, tuckpointing, windows, ADA accessibility, and interior buildout. The program reimburses up to 50% of eligible costs, with a maximum of $150,000 per storefront. Tenants and property owners both qualify. Applicants must obtain at least two contractor bids and work must not begin before approval.",
    requirements: ["Property in active TIF district", "Two contractor bids minimum", "Scope of work description", "Lease agreement or proof of ownership"],
    documentsRequired: [
      { name: "Lease Agreement", status: "have", description: "Current commercial lease showing property location" },
      { name: "Scope of Work", status: "need", description: "Detailed description of planned permanent improvements" },
      { name: "Contractor Bids", status: "need", description: "Minimum 2 bids from licensed contractors" },
      { name: "TIF Eligibility Verification", status: "need", description: "Confirm property is in active SBIF-eligible TIF district" },
    ],
    applicationUrl: "https://www.chicago.gov/city/en/depts/dcd/supp_info/small_business_improvementfund.html",
    tags: ["Chicago", "TIF", "building-improvement", "local"],
    isFavorited: true,
    pastAwardees: 6000,
    contactEmail: "sbif@cityofchicago.org",
    keyDates: [
      { label: "Application Cycle", date: "2026-04-30", description: "Current SBIF application cycle deadline" },
      { label: "Approvals", date: "2026-06-30", description: "Approved projects notified and agreements signed" },
    ],
    similarProgramIds: ["grant-012"],
  },
  {
    id: "grant-012",
    name: "Chicago Neighborhood Opportunity Fund (NOF)",
    agency: "City of Chicago Department of Planning and Development",
    agencyInitials: "DPD",
    type: "local",
    category: "grant",
    status: "open",
    amountMin: 2_500_000,
    amountMax: 25_000_000,
    averageAward: 10_000_000,
    deadline: "2026-05-15",
    matchScore: 68,
    matchStrength: "possible",
    eligibilityReasons: [
      { criterion: "Chicago-based business", met: true, explanation: "Located in Chicago, IL" },
      { criterion: "Project in qualifying neighborhood (South/West sides)", met: false, explanation: "West Loop is not in a qualifying NOF area — would need to open or relocate operations to an eligible neighborhood" },
      { criterion: "Commercial project with community benefit", met: true, explanation: "IT services could provide tech training and jobs" },
    ],
    shortDescription: "Grants from $25K to $250K for commercial projects in Chicago's underinvested South and West side neighborhoods.",
    fullDescription: "The Neighborhood Opportunity Fund supports commercial development in Chicago's historically underinvested areas, primarily on the South and West sides. Funded by fees from downtown zoning bonuses, NOF provides grants for new construction, renovation, expansion, and tenant buildout. Small grants ($25K-$250K) and large grants ($250K+) are available. Projects must be in qualifying neighborhoods and demonstrate community benefit through job creation, services, or economic activity. Minority-owned businesses receive priority consideration.",
    requirements: ["Project in NOF-eligible area", "Business plan", "Community benefit narrative", "Construction/renovation plans"],
    documentsRequired: [
      { name: "Location Verification", status: "need", description: "Proof that project is in NOF-eligible geography" },
      { name: "Project Plan", status: "need", description: "Construction or renovation plans with budget" },
      { name: "Community Benefit Statement", status: "need", description: "Description of jobs, services, and community impact" },
    ],
    applicationUrl: "https://www.chicago.gov/city/en/depts/dcd/supp_info/neighborhood-opportunity-fund0.html",
    tags: ["Chicago", "neighborhood", "development", "local"],
    isFavorited: false,
    pastAwardees: 400,
    contactEmail: "NOF@cityofchicago.org",
    keyDates: [
      { label: "Deadline", date: "2026-05-15", description: "Spring 2026 application cycle closes" },
      { label: "Awards", date: "2026-07-15", description: "Award decisions announced" },
    ],
    similarProgramIds: ["grant-011"],
  },
  {
    id: "grant-013",
    name: "Cook County Small Business Source Loan Program",
    agency: "Cook County Bureau of Economic Development",
    agencyInitials: "CBED",
    type: "local",
    category: "loan",
    status: "rolling",
    amountMin: 2_500_000,
    amountMax: 15_000_000,
    averageAward: 7_500_000,
    deadline: "2026-12-31",
    matchScore: 84,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Cook County business", met: true, explanation: "Chicago is in Cook County" },
      { criterion: "Under 50 employees or under $5M revenue", met: true, explanation: "12 employees, $1.8M revenue" },
      { criterion: "Need for working capital or equipment", met: true, explanation: "Growing IT firm with equipment and staffing needs" },
      { criterion: "Demonstrated ability to repay", met: true, explanation: "$1.8M revenue supports loan servicing" },
    ],
    shortDescription: "Low-interest microloans from $25K to $150K for Cook County small businesses through CDFI partners.",
    fullDescription: "The Cook County Small Business Source program provides low-interest loans through a network of Community Development Financial Institution (CDFI) partners. Loans range from $25,000 to $150,000 with below-market interest rates and flexible terms. Funds can be used for working capital, equipment purchases, leasehold improvements, and business expansion. The program prioritizes businesses in underserved suburban Cook County communities and those owned by minorities, women, and veterans. Chicago businesses are also eligible.",
    requirements: ["Application through CDFI partner", "Business plan", "Financial statements", "Use of funds description"],
    documentsRequired: [
      { name: "CDFI Application", status: "need", description: "Application through participating CDFI lender" },
      { name: "Business Plan", status: "need", description: "Plan showing use of funds and repayment ability" },
      { name: "Financial Statements", status: "have", description: "Last 2 years of business financials" },
      { name: "Tax Returns", status: "have", description: "Personal and business tax returns" },
    ],
    applicationUrl: "https://www.cookcountyil.gov/service/small-business-source",
    tags: ["Cook County", "microloan", "CDFI", "local"],
    isFavorited: false,
    pastAwardees: 500,
    contactEmail: "economic.development@cookcountyil.gov",
    keyDates: [
      { label: "Rolling", date: "2026-12-31", description: "Applications accepted year-round through CDFI partners" },
    ],
    similarProgramIds: ["grant-005", "grant-008"],
  },
  {
    id: "grant-014",
    name: "Chicago CDFI Fund — Small Dollar Loan Program",
    agency: "U.S. Treasury CDFI Fund / Chicago CDFI Partners",
    agencyInitials: "CDFI",
    type: "local",
    category: "loan",
    status: "rolling",
    amountMin: 500_000,
    amountMax: 5_000_000,
    averageAward: 2_500_000,
    deadline: "2026-12-31",
    matchScore: 80,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Small business in low-income or underserved area", met: true, explanation: "Minority-owned business qualifies for CDFI target market" },
      { criterion: "Cannot access traditional bank financing", met: true, explanation: "As a small firm, may lack collateral for conventional loans" },
      { criterion: "Need for small-dollar working capital", met: true, explanation: "Could use $5K-$50K for equipment, hiring, or marketing" },
    ],
    shortDescription: "Microloans from $5K to $50K through Treasury-certified CDFIs serving Chicago's small businesses.",
    fullDescription: "Community Development Financial Institutions (CDFIs) certified by the U.S. Treasury's CDFI Fund provide small-dollar loans to businesses that cannot access traditional bank financing. In Chicago, certified CDFIs include Accion Chicago, the Chicago Community Loan Fund, and the Local Enterprise Assistance Fund (LEAF). These lenders offer microloans with flexible terms, lower credit score requirements, and free business technical assistance. The CDFI Fund's Small Dollar Loan Program specifically supports loans under $50,000 to micro-enterprises.",
    requirements: ["Application with participating CDFI", "Basic business documentation", "Personal identification"],
    documentsRequired: [
      { name: "CDFI Application", status: "need", description: "Apply directly with Accion Chicago, CCLF, or LEAF" },
      { name: "Business License", status: "have", description: "City of Chicago business license" },
      { name: "Bank Statements", status: "have", description: "Last 3-6 months of business bank statements" },
    ],
    applicationUrl: "https://www.accionchicago.org/",
    tags: ["microloan", "CDFI", "Chicago", "local"],
    isFavorited: false,
    pastAwardees: 2000,
    contactEmail: "info@accionchicago.org",
    keyDates: [
      { label: "Rolling", date: "2026-12-31", description: "Applications accepted year-round" },
    ],
    similarProgramIds: ["grant-013"],
  },

  // ──────────────────────────────────────────────
  //  PRIVATE / FOUNDATION PROGRAMS (4)
  // ──────────────────────────────────────────────
  {
    id: "grant-015",
    name: "Comcast RISE Investment Fund",
    agency: "Comcast Corporation",
    agencyInitials: "RISE",
    type: "private",
    category: "grant",
    status: "rolling",
    amountMin: 500_000,
    amountMax: 1_000_000,
    averageAward: 1_000_000,
    deadline: "2026-12-31",
    matchScore: 85,
    matchStrength: "strong",
    eligibilityReasons: [
      { criterion: "Small business owned by a person of color", met: true, explanation: "Minority-owned business" },
      { criterion: "US-based business", met: true, explanation: "Chicago, IL" },
      { criterion: "In business for 1+ years", met: true, explanation: "4 years operational" },
      { criterion: "Independently owned (not a franchise)", met: true, explanation: "Independent LLC" },
    ],
    shortDescription: "Grants of up to $10K plus marketing, technology, and media support for businesses owned by people of color.",
    fullDescription: "Comcast RISE (Representation, Investment, Strength, Empowerment) provides a package of support to small businesses owned by people of color. Selected businesses receive a combination of monetary grants (up to $10,000), Effectv marketing and advertising services, technology upgrades and equipment from Comcast Business, and consulting from Comcast mentors. The program selects new recipients monthly and has supported over 13,000 businesses since 2020. Recipients also receive visibility through Comcast's media platforms.",
    requirements: ["Online application", "Business description", "Impact narrative"],
    documentsRequired: [
      { name: "Online Application", status: "need", description: "Submit via comcastrise.com" },
      { name: "Business Description", status: "need", description: "Overview of business, goals, and community impact" },
    ],
    applicationUrl: "https://www.comcastrise.com/",
    tags: ["diversity", "technology", "marketing", "private"],
    isFavorited: false,
    pastAwardees: 13000,
    contactEmail: "rise@comcast.com",
    keyDates: [
      { label: "Monthly Selection", date: "2026-12-31", description: "New recipients selected each month — apply anytime" },
    ],
    similarProgramIds: ["grant-018"],
  },
  {
    id: "grant-016",
    name: "FedEx Small Business Grant Contest",
    agency: "FedEx Corporation",
    agencyInitials: "FEDEX",
    type: "private",
    category: "grant",
    status: "open",
    amountMin: 1_500_000,
    amountMax: 5_000_000,
    averageAward: 2_500_000,
    deadline: "2026-05-31",
    matchScore: 58,
    matchStrength: "worth-exploring",
    eligibilityReasons: [
      { criterion: "US-based small business", met: true, explanation: "Chicago, IL" },
      { criterion: "For-profit, 6+ months in operation", met: true, explanation: "4 years operational, LLC" },
      { criterion: "Annual revenue under $5M", met: true, explanation: "$1.8M revenue" },
    ],
    shortDescription: "Annual contest awarding $15K-$50K grants to US small businesses — winners chosen by public vote and judges.",
    fullDescription: "The FedEx Small Business Grant Contest is an annual competition that awards cash grants to US small businesses. Grand prize winners receive $50,000, with additional prizes of $30,000, $25,000, $20,000, and $15,000. The contest has two phases: an application and public voting phase, followed by judging. Businesses are evaluated on their story, innovation, community impact, and growth potential. The contest is highly competitive with thousands of entries, but it is free to enter and provides significant visibility even for non-winners through the voting phase.",
    requirements: ["Online entry form", "Business story and photos", "Public voting campaign"],
    documentsRequired: [
      { name: "Entry Form", status: "need", description: "Online application at fedexgrant.com" },
      { name: "Business Story", status: "need", description: "Written narrative about your business and impact" },
      { name: "Business Photos", status: "need", description: "Professional photos of business, team, and products" },
    ],
    applicationUrl: "https://www.fedex.com/en-us/small-business/grant-contest.html",
    tags: ["contest", "small-business", "private"],
    isFavorited: false,
    pastAwardees: 60,
    contactEmail: "smallbusiness@fedex.com",
    keyDates: [
      { label: "Entry Period", date: "2026-04-01", description: "Applications open" },
      { label: "Entry Deadline", date: "2026-05-31", description: "Last day to submit entries" },
      { label: "Voting Period", date: "2026-06-15", description: "Public voting opens" },
      { label: "Winners Announced", date: "2026-08-01", description: "Grand prize and runner-up winners announced" },
    ],
    similarProgramIds: ["grant-015"],
  },
  {
    id: "grant-017",
    name: "Verizon Small Business Digital Ready Program",
    agency: "Verizon Communications",
    agencyInitials: "VZ",
    type: "private",
    category: "grant",
    status: "rolling",
    amountMin: 1_000_000,
    amountMax: 1_000_000,
    averageAward: 1_000_000,
    deadline: "2026-12-31",
    matchScore: 78,
    matchStrength: "possible",
    eligibilityReasons: [
      { criterion: "US-based small business", met: true, explanation: "Chicago, IL" },
      { criterion: "Revenue under $1.5M or fewer than 50 employees", met: true, explanation: "12 employees" },
      { criterion: "Complete required online courses", met: false, explanation: "Must complete at least 2 learning modules on the platform before applying for grant" },
    ],
    shortDescription: "Free online courses, 1:1 coaching, and $10K grants for small businesses building digital skills.",
    fullDescription: "Verizon Small Business Digital Ready is a free platform offering online courses, expert coaching, and peer networking for small business owners. Businesses that complete the program's learning modules become eligible to apply for $10,000 grants, which are awarded quarterly. The platform covers topics including digital marketing, social media, cybersecurity, financial management, and business resilience. The program has committed to distributing $1M in grants per quarter. Priority is given to businesses in underserved communities and those owned by women, minorities, and veterans.",
    requirements: ["Create free account", "Complete 2+ learning modules", "Apply during grant window"],
    documentsRequired: [
      { name: "Platform Account", status: "need", description: "Free registration at verizondigitalready.com" },
      { name: "Course Completions", status: "need", description: "Complete at least 2 online learning modules" },
      { name: "Grant Application", status: "need", description: "Apply during quarterly grant application window" },
    ],
    applicationUrl: "https://www.verizon.com/about/responsibility/digital-inclusion/small-business-digital-ready",
    tags: ["digital", "training", "grant", "private"],
    isFavorited: false,
    pastAwardees: 3500,
    contactEmail: "digitalgrants@verizon.com",
    keyDates: [
      { label: "Q2 Grant Window", date: "2026-06-01", description: "Q2 2026 grant application window opens" },
      { label: "Q2 Deadline", date: "2026-06-30", description: "Q2 grant applications close" },
      { label: "Q2 Awards", date: "2026-07-31", description: "Q2 grant recipients announced" },
    ],
    similarProgramIds: ["grant-015"],
  },
  {
    id: "grant-018",
    name: "Visa Everywhere Initiative",
    agency: "Visa Inc.",
    agencyInitials: "VISA",
    type: "private",
    category: "grant",
    status: "open",
    amountMin: 2_500_000,
    amountMax: 10_000_000,
    averageAward: 5_000_000,
    deadline: "2026-07-31",
    matchScore: 55,
    matchStrength: "worth-exploring",
    eligibilityReasons: [
      { criterion: "Technology or fintech company", met: true, explanation: "IT services with potential fintech applications" },
      { criterion: "Solution addressing payment/commerce challenges", met: false, explanation: "Would need to frame IT solutions around payment technology, cybersecurity for financial systems, or digital commerce" },
      { criterion: "Pre-Series B or bootstrapped", met: true, explanation: "Bootstrapped company with $1.8M revenue" },
    ],
    shortDescription: "Up to $100K for startups and small businesses solving challenges in payments, commerce, and financial services.",
    fullDescription: "The Visa Everywhere Initiative is a global innovation program that invites startups and small businesses to solve challenges in payments, commerce, financial inclusion, and cybersecurity. Regional winners receive cash prizes of $25,000 to $100,000, plus access to Visa's partner network, APIs, and potential pilot opportunities. The program runs regional competitions throughout the year, with a North America cycle typically in Q2-Q3. IT services companies can participate if they have solutions related to payment security, digital commerce, identity verification, or financial data analytics.",
    requirements: ["Online application", "Solution pitch (written + video)", "Technical demo or prototype"],
    documentsRequired: [
      { name: "Application Form", status: "need", description: "Online application at visaeverywhereinitative.com" },
      { name: "Solution Pitch", status: "need", description: "Written description and 3-minute video pitch" },
      { name: "Technical Demo", status: "need", description: "Prototype or working demo of solution" },
    ],
    applicationUrl: "https://www.visa.com/everywhere-initiative",
    tags: ["fintech", "payments", "innovation", "private"],
    isFavorited: false,
    pastAwardees: 150,
    contactEmail: "everywhere@visa.com",
    keyDates: [
      { label: "North America Opens", date: "2026-05-01", description: "North America regional applications open" },
      { label: "Deadline", date: "2026-07-31", description: "North America applications close" },
      { label: "Finals", date: "2026-10-15", description: "Regional finalists pitch to judges" },
    ],
    similarProgramIds: ["grant-016"],
  },
];
